export const data = [
  {
    id: 0,
    title: '1st-meet',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    // TODO: 이거 Date로 처리 안하면 후회하지 않을까?
    date: '01.07',
    customClass: 'dailybook-first',
    coverImage: './images/23.01.07.webp',
  },
  {
    id: 1,
    title: 'Haru-film',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.12',
    customClass: 'dailybook-second',
    coverImage: './images/23.01.12.webp',
  },
  {
    id: 2,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.14',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 3,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.16',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 4,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.18',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 5,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.20',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 6,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.22',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 7,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.24',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 8,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.26',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 9,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.27',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 10,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.28',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 11,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.29',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
  {
    id: 12,
    title: 'Network',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.30',
    customClass: 'dailybook-third',
    coverImage: './images/23.01.14.webp',
  },
];
