export const LANDING_INDEX_COUNT = 1;
export const MAX_DIAL_COUNT = 6;
export const START_DIAL_DEGREE = 90;
export const ROTATE_DEGREE = 45;

export const data = [
  {
    id: 0,
    title: 'First-Meeting',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.07',
    customClass: 'dailybook0',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 1,
    title: 'Haru-Film',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.12',
    customClass: 'dailybook1',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 2,
    title: 'Team',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.14',
    customClass: 'dailybook2',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 3,
    title: 'Recreation',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '01.28',
    customClass: 'dailybook3',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 4,
    title: 'Climbing',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.04',
    customClass: 'dailybook4',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 5,
    title: 'Online-Meeting',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.09',
    customClass: 'dailybook5',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 6,
    title: 'Climbing',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.11',
    customClass: 'dailybook6',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 7,
    title: 'Alver-Cafe',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.16',
    customClass: 'dailybook7',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 8,
    title: 'Zep-Meeting',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.18',
    customClass: 'dailybook8',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 9,
    title: 'Self-Photo',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.19',
    customClass: 'dailybook9',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
  {
    id: 10,
    title: 'Nex-Burning',
    description: 'Gallery of our memories that we met at Nexters 22nd',
    date: '02.25',
    customClass: 'dailybook10',
    coverImage:
      'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
    detail: {
      bgColor: 'rgb(167,188,217)',
      date: '02.01',
      keywords: [
        'Haru Firm',
        'First Picture',
        'MZ Culture',
        'Picture Keyword 1',
        'How We Play',
      ],
      descriptionTitle: 'First Meet',
      description:
        'We met for the first time at the orientation of the 22nd generation of Nexters. Young-hwan was absent due to work, but the others gathered together to greet each other.',
      imgSrcs: [
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230107/230107_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230112/230112_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230114/230114_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230128/230128_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230204/230204_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230209/230209_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230211/230211_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230216/230216_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230218/230218_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230219/230219_00.webp',
        'https://raw.githubusercontent.com/Nexters/who-really-wants-to-play/images/images/230225/230225_00.webp',
      ],
    },
  },
];
